config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  resources :users, only: [:show, :index]
  resources :stadiums
  resources :trips

  resource :inbox, :controller => 'inbox', :only => [:show,:create]

end

app/models/stadium.rb
class Stadium < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  mount_uploader :seating_chart, PhotoUploader

  has_many :trips

  validates :name,
    presence: true
  validates :city,
    presence: true
  validates :state,
    presence: true
  validates :capacity,
    presence: true
  validates :playing_surface,
    presence: true
  validates :roof_type,
    presence: true
  validates :team,
    presence: true
  validates :year,
    presence: true
end

app/models/trip.rb
class Trip < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  validates :username, presence: true, uniqueness: true, length: { in: (8..32) }
  validates :email, presence: true


  has_many :trips

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username, :profile_photo]
  end
end

app/controllers/inbox_controller.rb
class InboxController < ApplicationController
  include Mandrill::Rails::WebHookProcessor
end

app/controllers/stadiums_controller.rb
class StadiumsController < ApplicationController
  def index
   @stadiums = Stadium.all
  end

  def show
   @stadium = Stadium.find(params[:id])
  end
end

app/controllers/trips_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
 :method => :delete<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
   <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Fan Expeirence</a></h1>
    </li>

  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"> <% if !user_signed_in? %> <%= link_to "Stadiums", stadiums_path %> </li>
        <li class="active"><%= link_to "Sign up", new_user_registration_path %></li>
      <% elsif user_signed_in? %>
        <li class="active"> <%= link_to "Stadiums", stadiums_path %></li>
        <li class="active"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      <% end %>
     </ul>
    <ul class="left">
      <li class="has-form">
  <div class="row collapse">
    <div class="large-8 small-9 columns">
      <input type="text" placeholder="Search Stadiums">
    </div>
    <div class="large-4 small-3 columns">
      <a href="#" class="alert button expand">Search</a>
    </div>
  </div>
</li>
    </ul>
  </section>
</nav>



    <%= yield %>

  </body>
</html>

app/views/stadiums/index.html.erb
Here is a list of Stadioums:
<ul>
<% @stadiums.each do |stadium| %>
  <li><%= link_to stadium.name, stadium_path(stadium) %>
</ul>
<% end %>

app/views/stadiums/show.html.erb
<h2>  Stadium: <%= @stadium.name %> </h2>
  <div>
    <%= image_tag @stadium['photo'] %>
  </div>
  <div>
    Location: <%=@stadium.city %>, <%= @stadium.state %>
  </div>
  <div>
    Capacity: <%= (@stadium.capacity)%>
  </div>
  <div>
    Playing Surface: <%=@stadium.playing_surface %>
  </div>
  <div>
     Roof Type: <%=@stadium.roof_type%>
  </div>
  <div>
    TEAM: <%=@stadium.team %>
  </div>
  <div>
    <%=image_tag @stadium['seating_chart'] %>
  </div>
  <div>
   Description: ß<%=@stadium.description %>
  </div>